// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxDgGyN1Kj0aUvdVOuVgtPx_eyGJVgqK0',
    appId: '1:960986626957:web:bd9e8bd71ebe86f95a9bc4',
    messagingSenderId: '960986626957',
    projectId: 'car-rental-bd475',
    authDomain: 'car-rental-bd475.firebaseapp.com',
    storageBucket: 'car-rental-bd475.appspot.com',
    measurementId: 'G-R26K9VX3QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS4W1s0POSD9Png6DdgSxdeJeoV1BBXw4',
    appId: '1:960986626957:android:6c49d1f3ff9f0d7f5a9bc4',
    messagingSenderId: '960986626957',
    projectId: 'car-rental-bd475',
    storageBucket: 'car-rental-bd475.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYBoiGibSUBCClvrGnJ0JyIO8U_M3aKS4',
    appId: '1:960986626957:ios:9cef22eab88a01405a9bc4',
    messagingSenderId: '960986626957',
    projectId: 'car-rental-bd475',
    storageBucket: 'car-rental-bd475.appspot.com',
    iosBundleId: 'com.example.cRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYBoiGibSUBCClvrGnJ0JyIO8U_M3aKS4',
    appId: '1:960986626957:ios:c4b88868eb19b66d5a9bc4',
    messagingSenderId: '960986626957',
    projectId: 'car-rental-bd475',
    storageBucket: 'car-rental-bd475.appspot.com',
    iosBundleId: 'com.example.cRental.RunnerTests',
  );
}
